- name: create consul group
  sudo: yes
  group: name={{consul_group}}

- name: create consul user
  sudo: yes
  user: >
    name={{consul_user}}
    group={{consul_group}}
    system=yes

- name: create consul directory
  sudo: yes
  file: >
    state=directory
    path={{item}}
    owner={{consul_user}}
    group={{consul_group}}
  with_items:
    - "{{ consul_home }}"
    - "{{ consul_home }}/bin"
#    - "{{ consul_home }}/cert"
    - "{{ consul_data_dir }}"
    - "{{ consul_config_dir }}"

- name: check if consul_download is cached
  shell: echo "{{consul_archive_sha256}}  {{consul_download_folder}}/{{consul_archive}}" | sha256sum -c --status
  register: check_download
  failed_when: false
  changed_when: false

- name: download consul
  get_url:
    url: '{{consul_download}}'
    dest: '{{consul_download_folder}}'
    sha256sum: '{{consul_archive_sha256}}'
#    checksum: sha256:{{consul_archive_sha256}}
  register: consul_was_downloaded
  when: check_download.rc != 0

- name: copy and unpack
  sudo: yes
  unarchive:
    src: '{{ consul_download_folder }}/{{ consul_archive }}'
    dest: '{{ consul_home }}/bin'
    copy: no
  when: check_download.rc != 0 or consul_was_downloaded|changed

- name: set ownership
  sudo: yes
  file: >
    state=directory
    path={{consul_home}}
    owner={{consul_user}}
    group={{consul_group}}
    recurse=yes
  when: check_download.rc != 0 or consul_was_downloaded|changed

- name: profile hook, to publish consul_home variable and add consul to path
  sudo: yes
  template:
     src: profile_d.consul.sh.j2
     dest: /etc/profile.d/consul.sh
     owner: root
     group: root
     mode: 0755

- name: consul config file
  sudo: yes
  template:
    src: consul.conf.j2
    dest: '{{ consul_config_file }}'
    owner: '{{consul_user}}'
    group: '{{consul_group}}'
    mode: 0644
  notify:
    - restart consul

- name: validate consul is operational
  command: "{{ consul_home }}/bin/consul --version |grep -q 'Consul v{{ consul_version }}'"
  changed_when: false
