---

- name: consul iptables config
  become: yes
  lineinfile: dest=/etc/sysconfig/iptables
              line="-A INPUT -s {{item}}/32 -j ACCEPT"
              insertbefore="^COMMIT$"
  with_items: "{{consul_firewall_sources}}"
  notify:
    - reload iptables
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

- block:
  - name: systemctl status firewalld
    shell: "systemctl status firewalld | grep -q 'Active: active (running)'"
    changed_when: false
    failed_when: false
    register: r

  - name: consul firewalld config
    become: yes
    firewalld: >
      source="{{item}}/32"
      zone=trusted
      state=enabled
      immediate=yes
      permanent=yes
    with_items: "{{consul_firewall_sources}}"
    when: r.rc == 0

  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- block:
  - name: consul ufw rules
    become: yes
    ufw: rule=allow src="{{item}}/32"
    with_items: "{{consul_firewall_sources}}"

  when: ansible_os_family == 'Debian'
