---
- include: centos/prepare.yml
  when: ansible_os_family == 'RedHat'

- include: common.yml

- include: centos/postinstall.yml
  when: ansible_os_family == 'RedHat'

- include: firewall.yml
  when: consul_firewall_sources is defined
