---
- include: centos/prepare.yml
  when: ansible_os_family == 'RedHat'

- include: common.yml

- include: install-ui.yml
  when: consul_is_ui == true

- include: centos/postinstall.yml
  when: ansible_os_family == 'RedHat'

- include: debian/postinstall.yml
  when: ansible_os_family == 'Debian'

- include: firewall.yml
  when: consul_firewall_sources is defined
