---
- name: restart consul
  become: yes
  action: service name=consul state=restarted

- name: reload systemd
  become: yes
  command: systemctl daemon-reload
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
