---

- name: copy consul upstart script
  become: yes
  template:
    src: consul.upstart.j2
    dest: /etc/init/consul.conf
    owner: root
    group: root
    mode: 0755
  register: consul_script
  notify:
    - restart consul

- name: ensure consul started
  become: yes
  service: name=consul state=started enabled=yes
  when: not consul_script|changed
